version: '3.7'

volumes:
  openvpn_config:
  db_data:
#networks:
#   frontend:
#    external: true
#   backend:
#    external: true

services:
  openvpn:
    container_name: openvpn
    image: 373633196736.dkr.ecr.eu-west-2.amazonaws.com/openvpn-server:latest
    cap_add:
        - NET_ADMIN
    ports:
        - $HOST_SSL_PORT:$HOST_SSL_PORT/tcp
    environment:
      - HOST_ADDR
      - HOST_SSL_PORT
      - OPENVPN_ADMIN_USER
      - OPENVPN_ADMIN_PASSWORD
      - OPENVPN_APP_NAME
      - EASYRSA_KEY_SIZE
      - EASYRSA_CA_EXPIRE
      - EASYRSA_CERT_EXPIRE
      - EASYRSA_REQ_COUNTRY
      - EASYRSA_REQ_PROVINCE
      - EASYRSA_REQ_CITY
      - EASYRSA_REQ_ORG
      - EASYRSA_REQ_OU
      - EASYRSA_REQ_EMAIL
      - EASYRSA_REQ_CN
      - EASYRSA_BATCH
    volumes:
       - openvpn_config:/etc/openvpn
    restart: always
    command: tail -f /dev/null

  db:
    image: mariadb:latest
    container_name: db
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${OPENVPN_ADMIN_DATABASE}
      MYSQL_USER: ${OPENVPN_ADMIN_USER}
      MYSQL_PASSWORD: ${OPENVPN_ADMIN_PASSWORD}
    volumes:
      - db_data:/media/ssd/mysql
  googleauth:
    container_name: googleauth
    image: 373633196736.dkr.ecr.eu-west-2.amazonaws.com/openvpn-googleauth:latest

  webadmin:
    container_name: webadmin 
    depends_on:
      - openvpn
    image: 373633196736.dkr.ecr.eu-west-2.amazonaws.com/openvpn-webui:latest
    ports:
      - 8888:80
    volumes:
      - openvpn_config:/etc/openvpn
    environment:
      - OPENVPN_ADMIN_USER
      - OPENVPN_ADMIN_PASSWORD
      - OPENVPN_ADMIN_DATABASE
      - OPENVPN_APP_NAME
      - HOST_ADDR
      - HOST_SSL_PORT
      - OPENVPN_SERVER_ADDR
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

    command: sh -c "/usr/local/bin/start.sh & cron -f"
    
